$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: .
command: python model.py --trainingdata ${{inputs.training_data}}

environment: azureml://registries/azureml/environments/sklearn-1.1/versions/14
compute: azureml:jahanzaib
experiment_name: activity_12345
description: Human Activity Recognition classification
inputs:
  training_data:
    type: uri_file
    path: azureml:har_1:1
